services:
  veteran_web_app:
    build:
      context: .
    ports:
      - "8000:8000" # Adjust the port as needed
    environment:
      - DB_URL=postgresql://postgres:password@service_db:5432/veteran_app_db
      - OPENAI_API_KEY=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

    depends_on:
      - service_db

  service_db:
    image: postgres:latest
    container_name: service_db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: veteran_app_db
    ports:
      - "5432:5432"
    volumes:
      - veteran_app_db_data:/var/lib/postgresql/data

volumes:
  veteran_app_db_data:
